# Generated by Django 3.0.2 on 2020-02-02 00:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('url', models.URLField(max_length=255)),
                ('country', models.CharField(max_length=55)),
                ('to_scrape', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=255)),
                ('section', models.CharField(max_length=55)),
                ('subsection', models.CharField(max_length=100)),
                ('Keywords', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=55)),
                ('headline', models.CharField(max_length=255)),
                ('content_length', models.IntegerField()),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.TextField()),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_publisher', to='articles.Publisher')),
            ],
        ),
    ]
