# Generated by Django 3.0.2 on 2020-01-03 15:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='SourceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=55)),
                ('name', models.CharField(max_length=55)),
                ('description', models.TextField()),
                ('url', models.URLField(max_length=255)),
                ('language', models.CharField(max_length=55)),
                ('country', models.CharField(max_length=55)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_category', to='articles.SourceCategory')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=55)),
                ('title', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('url', models.URLField(max_length=255)),
                ('url_image', models.URLField(max_length=255)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_category', to='articles.ArticleCategory')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_source', to='articles.Source')),
            ],
        ),
    ]
