# Generated by Django 3.0.2 on 2020-01-03 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='to_scrape',
            field=models.BooleanField(default=False),
        ),
    ]
