# Generated by Django 3.0.2 on 2020-02-02 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='Keywords',
            new_name='keywords',
        ),
    ]
